/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_connolly_david_pgs_Render */

#ifndef _Included_name_connolly_david_pgs_Render
#define _Included_name_connolly_david_pgs_Render
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     name_connolly_david_pgs_Render
 * Method:    registerProgressSink
 * Signature: (Lname/connolly/david/pgs/util/ProgressSink;II)V
 */
JNIEXPORT void JNICALL Java_name_connolly_david_pgs_Render_registerProgressSink
	(JNIEnv * env, jobject obj, jobject progress);
	
/*
 * Class:     name_connolly_david_pgs_Render
 * Method:    openSubtitle
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_name_connolly_david_pgs_Render_openSubtitle
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     name_connolly_david_pgs_Render
 * Method:    closeSubtitle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_name_connolly_david_pgs_Render_closeSubtitle
  (JNIEnv *, jobject);

/*
 * Class:     name_connolly_david_pgs_Render
 * Method:    changeDetect
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_name_connolly_david_pgs_Render_changeDetect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     name_connolly_david_pgs_Render
 * Method:    getEventCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_name_connolly_david_pgs_Render_getEventCount
  (JNIEnv *, jobject);

/*
 * Class:     name_connolly_david_pgs_Render
 * Method:    getEventTimecode
 * Signature: (I)Lname/connolly/david/pgs/Timecode;
 */
JNIEXPORT jobject JNICALL Java_name_connolly_david_pgs_Render_getEventTimecode
  (JNIEnv *, jobject, jint);

/*
 * Class:     name_connolly_david_pgs_Render
 * Method:    render
 * Signature: (Ljava/awt/image/BufferedImage;J)V
 */
JNIEXPORT void JNICALL Java_name_connolly_david_pgs_Render_render
  (JNIEnv *, jobject, jobject, jlong);

void throw_render_exception(JNIEnv *env, const char *msg);
int is_subtitle_open();
void sendRenderMessage(char *msg);
	
#ifdef __cplusplus
}
#endif
#endif
